### ISSUE TITLE
Duplicated results

### ISSUE THREAD

**Issue by cbizon** [TranslatorSRI/NameResolution#126] opened 2023-12-05 20:04 UTC
When searching "alkaloid" or "alkaloids" it appears that the top answer is returning twice, followed by other answers returning once.

**Comment by gaurav** [comment] 2024-10-16 01:17
I think thus turned out to be caused by a duplicated load somewhere; I don't think we've had this issue again and it's not present now (for "alkaloid" or "alkaloids", at least). Closing.

**Closed by gaurav** 2024-10-16 01:17 UTC
